# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171124_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(help_text="Set book's natural language", max_length=200),
        ),
    ]
